CREATE TABLE IF NOT EXISTS Tasks (
    id VARCHAR(36) PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    done BOOLEAN
);

CREATE TABLE IF NOT EXISTS Stats (
    timestamp VARCHAR DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    open BIGINT DEFAULT 0,
    done BIGINT DEFAULT 0
);