// Generated by `wit-bindgen` 0.18.0. DO NOT EDIT!
pub mod fermyon {
  pub mod hmac {
    
    #[allow(clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      #[cfg(target_arch = "wasm32")]
      static __FORCE_SECTION_REF: fn() = super::super::super::__link_section;
      pub type Error = wit_bindgen::rt::string::String;
      
    }
    
    
    #[allow(clippy::all)]
    pub mod sign {
      #[used]
      #[doc(hidden)]
      #[cfg(target_arch = "wasm32")]
      static __FORCE_SECTION_REF: fn() = super::super::super::__link_section;
      pub type Error = super::super::super::fermyon::hmac::types::Error;
      #[allow(unused_unsafe, clippy::all)]
      pub fn sign(data: &[u8],keyvalue: &[u8],) -> Result<wit_bindgen::rt::vec::Vec::<u8>,Error>{
        
        #[allow(unused_imports)]
        use wit_bindgen::rt::{alloc, vec::Vec, string::String};
        unsafe {
          
          #[repr(align(4))]
          struct RetArea([u8; 12]);
          let mut ret_area = ::core::mem::MaybeUninit::<RetArea>::uninit();
          let vec0 = data;
          let ptr0 = vec0.as_ptr() as i32;
          let len0 = vec0.len() as i32;
          let vec1 = keyvalue;
          let ptr1 = vec1.as_ptr() as i32;
          let len1 = vec1.len() as i32;
          let ptr2 = ret_area.as_mut_ptr() as i32;
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "fermyon:hmac/sign@0.1.0")]
          extern "C" {
            #[link_name = "sign"]
            fn wit_import(_: i32, _: i32, _: i32, _: i32, _: i32, );
          }
          
          #[cfg(not(target_arch = "wasm32"))]
          fn wit_import(_: i32, _: i32, _: i32, _: i32, _: i32, ){ unreachable!() }
          wit_import(ptr0, len0, ptr1, len1, ptr2);
          let l3 = i32::from(*((ptr2 + 0) as *const u8));
          match l3 {
            0 => {
              let e = {
                let l4 = *((ptr2 + 4) as *const i32);
                let l5 = *((ptr2 + 8) as *const i32);
                let len6 = l5 as usize;
                
                Vec::from_raw_parts(l4 as *mut _, len6, len6)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l7 = *((ptr2 + 4) as *const i32);
                let l8 = *((ptr2 + 8) as *const i32);
                let len9 = l8 as usize;
                let bytes9 = Vec::from_raw_parts(l7 as *mut _, len9, len9);
                
                wit_bindgen::rt::string_lift(bytes9)
              };
              Err(e)
            }
            _ => wit_bindgen::rt::invalid_enum_discriminant(),
          }
        }
      }
      
    }
    
  }
}

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:signing"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 316] = [0, 97, 115, 109, 13, 0, 1, 0, 0, 25, 22, 119, 105, 116, 45, 99, 111, 109, 112, 111, 110, 101, 110, 116, 45, 101, 110, 99, 111, 100, 105, 110, 103, 4, 0, 7, 191, 1, 1, 65, 2, 1, 65, 5, 1, 66, 2, 1, 115, 4, 0, 5, 101, 114, 114, 111, 114, 3, 0, 0, 3, 1, 24, 102, 101, 114, 109, 121, 111, 110, 58, 104, 109, 97, 99, 47, 116, 121, 112, 101, 115, 64, 48, 46, 49, 46, 48, 5, 0, 2, 3, 0, 0, 5, 101, 114, 114, 111, 114, 1, 66, 6, 2, 3, 2, 1, 1, 4, 0, 5, 101, 114, 114, 111, 114, 3, 0, 0, 1, 112, 125, 1, 106, 1, 2, 1, 1, 1, 64, 2, 4, 100, 97, 116, 97, 2, 8, 107, 101, 121, 118, 97, 108, 117, 101, 2, 0, 3, 4, 0, 4, 115, 105, 103, 110, 1, 4, 3, 1, 23, 102, 101, 114, 109, 121, 111, 110, 58, 104, 109, 97, 99, 47, 115, 105, 103, 110, 64, 48, 46, 49, 46, 48, 5, 2, 4, 1, 39, 102, 101, 114, 109, 121, 111, 110, 58, 119, 101, 98, 104, 111, 111, 107, 115, 45, 112, 114, 111, 100, 117, 99, 101, 114, 47, 115, 105, 103, 110, 105, 110, 103, 64, 48, 46, 49, 46, 48, 4, 0, 11, 13, 1, 0, 7, 115, 105, 103, 110, 105, 110, 103, 3, 0, 0, 0, 70, 9, 112, 114, 111, 100, 117, 99, 101, 114, 115, 1, 12, 112, 114, 111, 99, 101, 115, 115, 101, 100, 45, 98, 121, 2, 13, 119, 105, 116, 45, 99, 111, 109, 112, 111, 110, 101, 110, 116, 6, 48, 46, 50, 49, 46, 48, 16, 119, 105, 116, 45, 98, 105, 110, 100, 103, 101, 110, 45, 114, 117, 115, 116, 6, 48, 46, 49, 56, 46, 48];

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_section() {}
